import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./variables.css";
import ThemeToggle from "@/components/themeToggle/themeToggle";
import UserContextProvider from "@/context/userContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeToggle />
        <UserContextProvider>{children}</UserContextProvider>
      </body>
    </html>
  );
}
